---
apiVersion: v1
kind: Service
metadata:
  name: arvis
  namespace: default
  labels:
    target: vcluster
spec:
  selector:
    app: vcluster
    release: arvis-managed-vcluster
  ports:
    - name: http
      port: 80
      targetPort: 8443
  type: LoadBalancer