---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  labels:
    userType: bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: admin
    namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-token
  annotations:
    kubernetes.io/service-account.name: admin
type: kubernetes.io/service-account-token