apiVersion: lib.projectsveltos.io/v1beta1
kind: EventSource
metadata:
  name: kubectl-secret-event-source
spec:
  collectResources: true
  resourceSelectors:
  - group: ""
    version: "v1"
    kind: "Secret"
    evaluate: |
      function evaluate()
        hs = {}
        hs.matching = false
        hs.message = obj.metadata.name .. " secret was not a matching kubeconfig"
        if string.find(obj.metadata.name, "managed-vcluster-kubectl-export", 1, true) then
          hs.matching = true
          hs.message = "kubeconfig found in secret " .. obj.metadata.name
        end
        return hs
      end